export const SUBMIT_FORM_INIT = 'SUBMIT_FORM_INIT';
export const SUBMIT_FORM_START = 'SUBMIT_FORM_START'
export const SUBMIT_FORM_FAIL = 'SUBMIT_FORM_FAIL'
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const FORM_SUBMITTED = 'FORM_SUBMITTED';