export const CHECK_AUTH_INIT = 'CHECK_AUTH_INIT';
export const CHECK_AUTH = 'CHECK_AUTH';
export const CHECK_AUTH_FAIL = 'CHECK_AUTH_FAIL';
export const CHECK_USERIMG = 'CHECK_USERIMG';
export const CHECK_USERNAME = 'CHECK_USERNAME';
export const LOGGED_IN = 'LOGGED_IN';

export const SUBMIT_AUTHFORMSIGNIN_INIT = 'SUBMIT_AUTHFORMSIGNIN_INIT';
export const SUBMIT_AUTHFORMSIGNUP_INIT = 'SUBMIT_AUTHFORMSIGNUP_INIT';
export const SUBMIT_AUTHFORMFORGETPASS_INIT = 'SUBMIT_AUTHFORMFORGETPASS_INIT';
export const SUBMIT_AUTHFORMRESETPASS_INIT = 'SUBMIT_AUTHFORMRESETPASS_INIT';
export const SUBMIT_AUTHFORM_START = 'SUBMIT_AUTHFORM_START'
export const SUBMIT_AUTHFORM_FAIL = 'SUBMIT_AUTHFORM_FAIL'
export const SUBMIT_AUTHFORM = 'SUBMIT_AUTHFORM';
export const AUTHFORM_SUBMITTED = 'AUTHFORM_SUBMITTED';
export const AUTHFORM_RESET = 'AUTHFORM_RESET';

export const HEADER_FILTER_INIT = 'HEADER_FILTER_INIT';
export const HEADER_FILTER_START = 'HEADER_FILTER_START';
export const HEADER_FILTER_FAIL = 'HEADER_FILTER_FAIL';
export const HEADER_FILTER = 'HEADER_FILTER';
export const HEADER_PAGE_CLOSE = 'HEADER_PAGE_CLOSE';

export const FETCH_CONV_INIT = 'FETCH_CONV_INIT';
export const FETCH_CONV = 'FETCH_CONV';
export const FETCH_CONV_START = 'FETCH_CONV_START';
export const FETCH_CONV_FAIL = 'FETCH_CONV_FAIL';

export const FETCH_NOTIFY_INIT = 'FETCH_NOTIFY_INIT';
export const FETCH_NOTIFY = 'FETCH_NOTIFY';
export const FETCH_NOTIFY_START = 'FETCH_NOTIFY_START';
export const FETCH_NOTIFY_FAIL = 'FETCH_NOTIFY_FAIL';

export const FETCH_PROFILE_INIT = 'FETCH_PROFILE_INIT';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_START = 'FETCH_PROFILE_START';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';
export const CHANGE_PROFILE_INIT = 'CHANGE_PROFILE_INIT';
export const CHANGE_PROFILE_FAIL = 'CHANGE_PROFILE_FAIL';
export const CHANGE_PROFILE_START = 'CHANGE_PROFILE_START';
export const CHANGE_PROFILE_CANCEL = 'CHANGE_PROFILE_CANCEL';
export const CHANGE_PROFILE_RESET= 'CHANGE_PROFILE_RESET';
export const CHANGE_PROFILE = 'CHANGE_PROFILE';
export const SUBMIT_ABOUT_INIT = 'SUBMIT_ABOUT_INIT';
export const SUBMIT_ABOUT_FAIL = 'SUBMIT_ABOUT_FAIL';
export const SUBMIT_ABOUT_START = 'SUBMIT_ABOUT_START';
export const SUBMIT_ABOUT_RESET = 'SUBMIT_ABOUT_RESET';
export const SUBMIT_ABOUT = 'SUBMIT_ABOUT';
export const SUBMIT_PROFILE_IMAGE_INIT = 'SUBMIT_PROFILE_IMAGE_INIT';
export const SUBMIT_PROFILE_IMAGE_FAIL = 'SUBMIT_PROFILE_IMAGE_FAIL';
export const SUBMIT_PROFILE_IMAGE_START = 'SUBMIT_PROFILE_IMAGE_START';
export const SUBMIT_PROFILE_IMAGE_RESET = 'SUBMIT_PROFILE_IMAGE_RESET';
export const SUBMIT_PROFILE_IMAGE = 'SUBMIT_PROFILE_IMAGE';
export const SUBMIT_USERNAME_INIT = 'SUBMIT_USERNAME_INIT';
export const SUBMIT_USERNAME_FAIL = 'SUBMIT_USERNAME_FAIL';
export const SUBMIT_USERNAME_START = 'SUBMIT_USERNAME_START';
export const SUBMIT_USERNAME_RESET = 'SUBMIT_USERNAME_RESET';
export const SUBMIT_USERNAME = 'SUBMIT_USERNAME';

export const SUBMIT_ADDFORM_INIT = 'SUBMIT_ADDFORM_INIT';
export const SUBMIT_ADDFORM_START = 'SUBMIT_ADDFORM_START'
export const SUBMIT_ADDFORM_FAIL = 'SUBMIT_ADDFORM_FAIL'
export const SUBMIT_ADDFORM = 'SUBMIT_ADDFORM';
export const ADDFORM_SUBMITTED = 'ADDFORM_SUBMITTED';
export const ADDFORM_RESET = 'POSTFORM_RESET';

export const FETCH_EDITFORM_INIT = 'FETCH_EDITFORM_INIT';
export const FETCH_EDITFORM_START = 'FETCH_EDITFORM_START'
export const FETCH_EDITFORM_FAIL = 'FETCH_EDITFORM_FAIL'
export const FETCH_EDITFORM = 'FETCH_EDITFORM';
export const SUBMIT_EDITFORM_INIT = 'SUBMIT_EDITFORM_INIT';
export const SUBMIT_EDITFORM_START = 'SUBMIT_EDITFORM_START'
export const SUBMIT_EDITFORM_FAIL = 'SUBMIT_EDITFORM_FAIL'
export const SUBMIT_EDITFORM = 'SUBMIT_EDITFORM';
export const EDITFORM_SUBMITTED = 'EDITFORM_SUBMITTED';
export const EDITFORM_RESET = 'POSTFORM_RESET';