export const CHECK_AUTH_INIT = 'CHECK_AUTH_INIT';
export const CHECK_AUTH = 'CHECK_AUTH';
export const CHECK_USERIMG = 'CHECK_USERIMG';
export const CHECK_USERNAME = 'CHECK_USERNAME';

export const HEADER_FORM_EXPAND = 'HEADER_FORM_EXPAND';
export const HEADER_FORM_SM = 'HEADER_FORM_SM';
export const HEADER_NAV_DEFAULT = 'HEADER_NAV_DEFAULT'

export const HEADER_FILTER_INIT = 'HEADER_FILTER_INIT';
export const HEADER_FILTER_START = 'HEADER_FILTER_START';
export const HEADER_FILTER_FAIL = 'HEADER_FILTER_FAIL';
export const HEADER_FILTER = 'HEADER_FILTER';
export const HEADER_FILTER_CLOSE = 'HEADER_FILTER_CLOSE';

export const HEADER_ADD_NEW = 'HEADER_ADD_NEW';

export const FETCH_NOTIFY_INIT = 'FETCH_NOTIFY_INIT';
export const FETCH_NOTIFY_START = 'FETCH_NOTIFY_START';
export const FETCH_NOTIFY_SUCCESS = 'FETCH_NOTIFY_SUCCESS';
export const FETCH_NOTIFY_FAIL = 'FETCH_NOTIFY_FAIL';
export const FETCH_NOTIFY = 'FETCH_NOTIFY';

export const CHANGE_FAVORITE_NOTIFY_INIT = 'CHANGE_FAVORITE_NOTIFY_INIT';
export const CHANGE_FAVORITE_NOTIFY_START = 'CHANGE_FAVORITE_NOTIFY_START';
export const CHANGE_FAVORITE_NOTIFY_FAIL = 'CHANGE_FAVORITE_NOTIFY_FAIL';
export const CHANGE_FAVORITE_NOTIFY = 'CHANGE_FAVORITE_NOTIFY';

export const SHOW_NAV_LIST = 'SHOW_NAV_LIST';
export const FETCH_NAVLIST_INIT = 'FETCH_NAVLIST_INIT';
export const FETCH_NAVLIST_START = 'FETCH_NAVLIST_START';
export const FETCH_NAVLIST_SUCCESS = 'FETCH_NAVLIST_SUCCESS';
export const FETCH_NAVLIST_FAIL = 'FETCH_NAVLIST_FAIL';
export const FETCH_NAVLIST = 'FETCH_NAVLIST';

export const SHOW_USER_OPTION = 'SHOW_USER_OPTION';

export const FETCH_SHARE_ACTIVE_INIT = 'FETCH_SHARE_ACTIVE_INIT';
export const FETCH_SHARE_ACTIVE = 'FETCH_SHARE_ACTIVE';
export const RESET_ACTIVE_INIT = 'RESET_ACTIVE_INIT';
export const RESET_ACTIVE = 'RESET_ACTIVE';

export const FETCH_NOTIFY_ACTIVE_INIT = 'FETCH_NOTIFY_ACTIVE_INIT';
export const FETCH_NOTIFY_ACTIVE = 'FETCH_NOTIFY_ACTIVE';
export const DEFAULT_NOTIFYACTIVE_INIT = 'DEFAULT_NOTIFYACTIVE_INIT';
export const DEFAULT_NOTIFYACTIVE = 'DEFAULT_NOTIFYACTIVE';

export const FETCH_CATEG_INIT = 'FETCH_CATEG_INIT';
export const FETCH_CATEG_START = 'FETCH_CATEG_START';
export const FETCH_CATEG_FAIL = 'FETCH_CATEG_FAIL';
export const FETCH_CATEG_RESET = 'FETCH_CATEG_RESET';
export const FETCH_CATEG = 'FETCH_CATEG';
export const ADD_CATEG_INIT = 'ADD_CATEG_INIT';
export const ADD_CATEG = 'ADD_CATEG';
export const HIDE_MEDIA_BOX = 'HIDE_MEDIA_BOX';
export const SHOW_MEDIA_BOX = 'SHOW_MEDIA_BOX';
export const CHECK_LINK_INIT = 'CHECK_LINK_INIT';
export const CHECK_LINK = 'CHECK_LINK';
export const RESET_LINK = 'RESET_LINK';
export const ADD_SNAPSHOT = 'ADD_SNAPSHOT';
export const REMOVE_SNAPSHOT = 'REMOVE_SNAPSHOT';
export const SUBMIT_MEDIA = 'SUBMIT_MEDIA';
export const FETCH_USERS_INIT ='FETCH_USERS_INIT';
export const FETCH_USERS_START ='FETCH_USERS_START';
export const FETCH_USERS_FAIL ='FETCH_USERS_FAIL';
export const FETCH_USERS ='FETCH_USERS';
export const INPUT_DEFAULT_VALUE = 'INPUT_DEFAULT_VALUE';
export const FILTER_USER_INIT = 'FILTER_USER_INIT';
export const FILTER_USER = 'FILTER_USER';
export const USER_SELECT = 'USER_SELECT';
export const REMOVE_MEDIA = 'REMOVE_MEDIA';
export const SHOW_USER_SELECT_INIT = 'SHOW_USER_SELECT_INIT';
export const SHOW_USER_SELECT = 'SHOW_USER_SELECT';
export const SUBMIT_FORM_INIT = 'SUBMIT_FORM_INIT';
export const SUBMIT_FORM_START = 'SUBMIT_FORM_START'
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS'
export const SUBMIT_FORM_FAIL = 'SUBMIT_FORM_FAIL'
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const FORM_SUBMITTED = 'FORM_SUBMITTED';