export const HEADER_FORM_EXPAND = 'HEADER_FORM_EXPAND';
export const HEADER_FORM_SM = 'HEADER_FORM_SM';
export const HEADER_NAV_DEFAULT = 'HEADER_NAV_DEFAULT'

export const HEADER_ADD_NEW = 'HEADER_ADD_NEW';

export const FETCH_NOTIFY_INIT = 'FETCH_NOTIFY_INIT';
export const FETCH_NOTIFY_START = 'FETCH_NOTIFY_START';
export const FETCH_NOTIFY_SUCCESS = 'FETCH_NOTIFY_SUCCESS';
export const FETCH_NOTIFY_FAIL = 'FETCH_NOTIFY_FAIL';
export const FETCH_NOTIFY = 'FETCH_NOTIFY';

export const CHANGE_FAVORITE_NOTIFY_INIT = 'CHANGE_FAVORITE_NOTIFY_INIT';
export const CHANGE_FAVORITE_NOTIFY_START = 'CHANGE_FAVORITE_NOTIFY_START';
export const CHANGE_FAVORITE_NOTIFY_FAIL = 'CHANGE_FAVORITE_NOTIFY_FAIL';
export const CHANGE_FAVORITE_NOTIFY = 'CHANGE_FAVORITE_NOTIFY';

export const SHOW_NAV_LIST = 'SHOW_NAV_LIST';
export const FETCH_NAVLIST_INIT = 'FETCH_NAVLIST_INIT';
export const FETCH_NAVLIST_START = 'FETCH_NAVLIST_START';
export const FETCH_NAVLIST_SUCCESS = 'FETCH_NAVLIST_SUCCESS';
export const FETCH_NAVLIST_FAIL = 'FETCH_NAVLIST_FAIL';
export const FETCH_NAVLIST = 'FETCH_NAVLIST';

export const SHOW_USER_OPTION = 'SHOW_USER_OPTION';

export const FETCH_MAINACTIVE_INIT = 'FETCH_MAINACTIVE_INIT';
export const FETCH_MAINACTIVE = 'FETCH_MAINACTIVE';
export const DEFAULT_MAINACTIVE_INIT = 'DEFAULT_MAINACTIVE_INIT';
export const DEFAULT_MAINACTIVE = 'DEFAULT_MAINACTIVE';

export const FETCH_NOTIFY_ACTIVE_INIT = 'FETCH_NOTIFY_ACTIVE_INIT';
export const FETCH_NOTIFY_ACTIVE = 'FETCH_NOTIFY_ACTIVE';
export const DEFAULT_NOTIFYACTIVE_INIT = 'DEFAULT_NOTIFYACTIVE_INIT';
export const DEFAULT_NOTIFYACTIVE = 'DEFAULT_NOTIFYACTIVE';
export const FETCH_SHARE_ACTIVE_INIT = 'FETCH_SHARE_ACTIVE_INIT';
export const FETCH_SHARE_ACTIVE = 'FETCH_SHARE_ACTIVE';

export const FETCH_PT_CATEG_INIT = 'FETCH_PT_CATEG_INIT';
export const FETCH_PT_CATEG = 'FETCH_PT_CATEG';
export const ADD_PT_CATEG_INIT = 'ADD_PT_CATEG_INIT';
export const ADD_PT_CATEG = 'ADD_PT_CATEG';
export const HIDE_MEDIA_BOX = 'HIDE_MEDIA_BOX';
export const SHOW_MEDIA_BOX = 'SHOW_MEDIA_BOX';
export const CHECK_LINK_INIT = 'CHECK_LINK_INIT';
export const CHECK_LINK = 'CHECK_LINK';
export const RESET_LINK = 'RESET_LINK';
export const SUBMIT_MEDIA = 'SUBMIT_MEDIA';