export const CHECK_AUTH_INIT = 'CHECK_AUTH_INIT';
export const CHECK_AUTH = 'CHECK_AUTH';
export const CHECK_AUTH_FAIL = 'CHECK_AUTH_FAIL';
export const CHECK_USERIMG = 'CHECK_USERIMG';
export const CHECK_USERNAME = 'CHECK_USERNAME';
export const LOGGED_IN = 'LOGGED_IN';

export const SUBMIT_AUTHFORMSIGNIN_INIT = 'SUBMIT_AUTHFORMSIGNIN_INIT';
export const SUBMIT_AUTHFORMSIGNUP_INIT = 'SUBMIT_AUTHFORMSIGNUP_INIT';
export const SUBMIT_AUTHFORMFORGETPASS_INIT = 'SUBMIT_AUTHFORMFORGETPASS_INIT';
export const SUBMIT_AUTHFORMRESETPASS_INIT = 'SUBMIT_AUTHFORMRESETPASS_INIT';
export const SUBMIT_AUTHFORM_START = 'SUBMIT_AUTHFORM_START'
export const SUBMIT_AUTHFORM_FAIL = 'SUBMIT_AUTHFORM_FAIL'
export const SUBMIT_AUTHFORM = 'SUBMIT_AUTHFORM';
export const AUTHFORM_SUBMITTED = 'AUTHFORM_SUBMITTED';
export const AUTHFORM_RESET = 'AUTHFORM_RESET';

export const HEADER_FILTER_INIT = 'HEADER_FILTER_INIT';
export const HEADER_FILTER_START = 'HEADER_FILTER_START';
export const HEADER_FILTER_FAIL = 'HEADER_FILTER_FAIL';
export const HEADER_FILTER = 'HEADER_FILTER';
export const HEADER_PAGE_CLOSE = 'HEADER_PAGE_CLOSE';

export const FETCH_CONV_INIT = 'FETCH_CONV_INIT';
export const FETCH_CONV = 'FETCH_CONV';
export const FETCH_CONV_START = 'FETCH_CONV_START';
export const FETCH_CONV_FAIL = 'FETCH_CONV_FAIL';

export const FETCH_NOTIFY_INIT = 'FETCH_NOTIFY_INIT';
export const FETCH_NOTIFY = 'FETCH_NOTIFY';
export const FETCH_NOTIFY_START = 'FETCH_NOTIFY_START';
export const FETCH_NOTIFY_FAIL = 'FETCH_NOTIFY_FAIL';

export const FETCH_PROFILE_INIT = 'FETCH_PROFILE_INIT';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_START = 'FETCH_PROFILE_START';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';
export const CHANGE_PROFILE_INIT = 'CHANGE_PROFILE_INIT';
export const CHANGE_PROFILE_FAIL = 'CHANGE_PROFILE_FAIL';
export const CHANGE_PROFILE_START = 'CHANGE_PROFILE_START';
export const CHANGE_PROFILE_CANCEL = 'CHANGE_PROFILE_CANCEL';
export const CHANGE_PROFILE_RESET= 'CHANGE_PROFILE_RESET';
export const CHANGE_PROFILE = 'CHANGE_PROFILE';