export const CHECK_AUTH_INIT = 'CHECK_AUTH_INIT';
export const CHECK_AUTH = 'CHECK_AUTH';
export const CHECK_USERIMG = 'CHECK_USERIMG';
export const CHECK_USERNAME = 'CHECK_USERNAME';

export const HEADER_FORM_EXPAND = 'HEADER_FORM_EXPAND';
export const HEADER_FORM_SM = 'HEADER_FORM_SM';
export const HEADER_NAV_DEFAULT = 'HEADER_NAV_DEFAULT'

export const HEADER_FILTER_INIT = 'HEADER_FILTER_INIT';
export const HEADER_FILTER_START = 'HEADER_FILTER_START';
export const HEADER_FILTER_FAIL = 'HEADER_FILTER_FAIL';
export const HEADER_FILTER = 'HEADER_FILTER';
export const HEADER_FILTER_CLOSE = 'HEADER_FILTER_CLOSE';

export const HEADER_ADD_NEW = 'HEADER_ADD_NEW';

export const FETCH_CNT_INIT = 'FETCH_CNT_INIT';
export const FETCH_CNT_START = 'FETCH_CNT_START';
export const FETCH_CNT_RESET = 'FETCH_CNT_RESET';
export const FETCH_CNT_FAIL = 'FETCH_CNT_FAIL';
export const FETCH_CNT = 'FETCH_CNT';

export const CHANGE_CNT_INIT = 'CHANGE_CNT_INIT';
export const CHANGE_CNT_FAIL = 'CHANGE_CNT_FAIL';
export const CHANGE_CNT_START = 'CHANGE_CNT_START';
export const CHANGE_CNT_CANCEL = 'CHANGE_CNT_CANCEL';
export const CHANGE_CNT_RESET= 'CHANGE_CNT_RESET';
export const CHANGE_CNT = 'CHANGE_CNT';

export const FILTER_POST = 'FILTER_POST';

export const FETCH_CNTCATEG_INIT = 'FETCH_CNTCATEG_INIT';
export const FETCH_CNTCATEG_START = 'FETCH_CNTCATEG_START';
export const FETCH_CNTCATEG = 'FETCH_CNTCATEG';

export const FETCH_VIDEO_INIT = 'FETCH_VIDEO_INIT';
export const FETCH_VIDEO_START = 'FETCH_VIDEO_START';
export const FETCH_VIDEO_FAIL = 'FETCH_VIDEO_FAIL';
export const FETCH_VIDEO = 'FETCH_VIDEO';

export const CHANGE_FAVORITE_INIT = 'CHANGE_FAVORITE_INIT';
export const CHANGE_FAVORITE_PT_START = 'CHANGE_FAVORITE_PT_START';
export const CHANGE_FAVORITE_PT_FAIL = 'CHANGE_FAVORITE_PT_FAIL'
export const CHANGE_FAVORITE = 'CHANGE_FAVORITE';

export const FETCH_USERS_INIT = 'FETCH_USERS_INIT';
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_USERS = 'FETCH_USERS';

export const USER_SELECT = 'USER_SELECT';
export const VIEW_USERS = 'VIEW_USERS';
export const REMOVE_USER = 'REMOVE_USER';
export const FILTER_USER_INIT = 'FILTER_USER_INIT';
export const FILTER_USER = 'FILTER_USER';
export const FILTER_USER_SELECT_INIT = 'FILTER_USER_SELECT_INIT';
export const FILTER_USER_SELECT = 'FILTER_USER_SELECT';
export const SHARE_ID = 'SHARE_ID';
export const SHARE_USER_INIT = 'SHARE_USER_INIT';
export const SHARE_USER_START = 'SHARE_USER_START';
export const SHARE_USER_FAIL = 'SHARE_USER_FAIL';
export const SHARE_USER = 'SHARE_USER';

export const CHANGE_TAGS_PATH = 'CHANGE_TAGS_PATH';
export const FETCH_TAGS_INIT = 'FETCH_TAGS_INIT';
export const FETCH_TAGS_START = 'FETCH_TAGS_START';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAIL = 'FETCH_TAGS_FAIL';
export const FETCH_TAGS_CATEG_INIT = 'FETCH_TAGS_CATEG_INIT';
export const FETCH_TAGS_CATEG_START = 'FETCH_TAGS_CATEG_START';
export const FETCH_TAGS_CATEG = 'FETCH_TAGS_CATEG';
export const FETCH_TAGS = 'FETCH_TAGS';

export const FETCH_TRD_INIT = 'FETCH_TRD_INIT';
export const FETCH_TRD_START = 'FETCH_TRD_START';
export const FETCH_TRD_SUCCESS = 'FETCH_TRD_SUCCESS';
export const FETCH_TRD_FAIL = 'FETCH_TRD_FAIL';
export const FETCH_TRD = 'FETCH_TRD';

export const FETCH_CATEG_INIT = 'FETCH_CATEG_INIT';
export const FETCH_CATEG_START = 'FETCH_CATEG_START';
export const FETCH_CATEG_SUCCESS = 'FETCH_CATEG_SUCCESS';
export const FETCH_CATEG_FAIL = 'FETCH_CATEG_FAIL';
export const FETCH_CATEG = 'FETCH_CATEG';

export const FETCH_CONV_INIT = 'FETCH_CONV_INIT';
export const FETCH_CONV_START = 'FETCH_CONV_START';
export const FETCH_CONV_SUCCESS = 'FETCH_CONV_SUCCESS';
export const FETCH_CONV_FAIL = 'FETCH_CONV_FAIL';
export const FETCH_CONV = 'FETCH_CONV';

export const JOIN_GRP_INIT = 'JOIN_GRP_INIT';
export const JOIN_GRP_START = 'JOIN_GRP_START';
export const JOIN_GRP_FAIL = 'JOIN_GRP_FAIL';
export const JOIN_GRP = 'JOIN_GRP';

export const FETCH_JOIN_ACTIVE_INIT = 'FETCH_JOIN_ACTIVE_INIT';
export const FETCH_JOIN_ACTIVE = 'FETCH_JOIN_ACTIVE';
export const REMOVE_REQUEST = 'REMOVE_REQUEST';

export const FETCH_INFO_INIT = 'FETCH_INFO_INIT';
export const FETCH_INFO_START = 'FETCH_INFO_START';
export const FETCH_INFO_FAIL = 'FETCH_INFO_FAIL';
export const FETCH_INFO = 'FETCH_INFO';
export const SET_GRP_INFO = 'SET_GRP_INFO';
export const RESET_INPUT_FILTER = 'RESET_INPUT_FILTER';
export const FILTER_GRPUSER_INIT = 'FILTER_GRPUSER_INIT';
export const FILTER_GRPUSER = 'FILTER_GRPUSER';
export const SHARE_CNT = 'SHARE_CNT';
export const SHARE_GRPUSER = 'SHARE_GRPUSER';
export const CHANGE_GRPCNT_INIT = 'CHANGE_GRPCNT_INIT';
export const CHANGE_GRPCNT_FAIL = 'CHANGE_GRPCNT_FAIL';
export const CHANGE_GRPCNT_START = 'CHANGE_GRPCNT_START';
export const CHANGE_GRPCNT_CANCEL = 'CHANGE_GRPCNT_CANCEL';
export const CHANGE_GRPCNT_RESET= 'CHANGE_GRPCNT_RESET';
export const CHANGE_GRPCNT = 'CHANGE_GRPCNT';
export const CHANGE_GRPCNT_STARTINIT = 'CHANGE_GRPCNT_STARTINIT';

export const FETCH_NOTIFY_INIT = 'FETCH_NOTIFY_INIT';
export const FETCH_NOTIFY_START = 'FETCH_NOTIFY_START';
export const FETCH_NOTIFY_SUCCESS = 'FETCH_NOTIFY_SUCCESS';
export const FETCH_NOTIFY_FAIL = 'FETCH_NOTIFY_FAIL';
export const FETCH_NOTIFY = 'FETCH_NOTIFY';

export const CHANGE_MAINFAVORITE_START = 'CHANGE_MAINFAVORITE_START';
export const CHANGE_MAINFAVORITE_RESET = 'CHANGE_MAINFAVORITE_RESET';

export const CHANGE_FAVORITE_NOTIFY_INIT = 'CHANGE_FAVORITE_NOTIFY_INIT';
export const CHANGE_FAVORITE_NOTIFY_START = 'CHANGE_FAVORITE_NOTIFY_START';
export const CHANGE_FAVORITE_NOTIFY_FAIL = 'CHANGE_FAVORITE_NOTIFY_FAIL';
export const CHANGE_FAVORITE_NOTIFY = 'CHANGE_FAVORITE_NOTIFY';

export const SHOW_NAV_LIST = 'SHOW_NAV_LIST';
export const FETCH_NAVLIST_INIT = 'FETCH_NAVLIST_INIT';
export const FETCH_NAVLIST_START = 'FETCH_NAVLIST_START';
export const FETCH_NAVLIST_SUCCESS = 'FETCH_NAVLIST_SUCCESS';
export const FETCH_NAVLIST_FAIL = 'FETCH_NAVLIST_FAIL';
export const FETCH_NAVLIST = 'FETCH_NAVLIST';

export const SHOW_USER_OPTION = 'SHOW_USER_OPTION';

export const FETCH_PT_ACTIVE_INIT = 'FETCH_PT_ACTIVE_INIT';
export const FETCH_PT_ACTIVE = 'FETCH_PT_ACTIVE';
export const FETCH_QUE_ACTIVE_INIT = 'FETCH_QUE_ACTIVE_INIT';
export const FETCH_QUE_ACTIVE = 'FETCH_QUE_ACTIVE';
export const FETCH_CNT_ACTIVE_INIT = 'FETCH_CNT_ACTIVE_INIT';
export const FETCH_CNT_ACTIVE = 'FETCH_CNT_ACTIVE';
export const FETCH_REQ_ACTIVE_INIT = 'FETCH_REQ_ACTIVE_INIT';
export const FETCH_REQ_ACTIVE = 'FETCH_REQ_ACTIVE';
export const FETCH_SHARE_ACTIVE_INIT = 'FETCH_SHARE_ACTIVE_INIT';
export const FETCH_SHARE_ACTIVE = 'FETCH_SHARE_ACTIVE';
export const FETCH_SHARECNT_ACTIVE_INIT = 'FETCH_SHARECNT_ACTIVE_INIT';
export const FETCH_SHARECNT_ACTIVE = 'FETCH_SHARECNT_ACTIVE';
export const RESET_ACTIVE_INIT = 'RESET_ACTIVE_INIT';
export const RESET_ACTIVE = 'RESET_ACTIVE';
export const FETCH_NAV_ACTIVE_INIT = 'FETCH_NAV_ACTIVE_INIT';
export const FETCH_NAV_ACTIVE = 'FETCH_NAV_ACTIVE';
export const SHOW_MAIN_BACKDROP= 'SHOW_MAIN_BACKDROP';
export const HIDE_MAIN_BACKDROP= 'HIDE_MAIN_BACKDROP';

export const FETCH_NOTIFY_ACTIVE_INIT = 'FETCH_NOTIFY_ACTIVE_INIT';
export const FETCH_NOTIFY_ACTIVE = 'FETCH_NOTIFY_ACTIVE';
export const DEFAULT_NOTIFYACTIVE_INIT = 'DEFAULT_NOTIFYACTIVE_INIT';
export const DEFAULT_NOTIFYACTIVE = 'DEFAULT_NOTIFYACTIVE';

export const FILTER_CONTENT_INIT = 'FILTER_CONTENT_INIT';
export const FILTER_CONTENT_START = 'FILTER_CONTENT_START';
export const FILTER_CONTENT_FAIL = 'FILTER_CONTENT_FAIL';
export const FILTER_CONTENT = 'FILTER_CONTENT';
export const RESET_FILTER = 'RESET_FILTER';

export const RESET_MODEL = 'RESET_MODEL';

export const FETCH_CHATDET_INIT = 'FETCH_CHATDET_INIT';
export const FETCH_CHATDET = 'FETCH_CHATDET';
export const FETCH_CHATDET_START = 'FETCH_CHATDET_START';
export const FETCH_CHATDET_FAIL = 'FETCH_CHATDET_FAIL';
export const SHOW_CHATDET = 'SHOW_CHATDET';


