export const FETCH_POST_INIT = 'FETCH_POST_INIT';
export const FETCH_POST_START = 'FETCH_POST_START';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL';
export const FETCH_POST = 'FETCH_POST';


export const CHANGE_FAVORITE_INIT = 'CHANGE_FAVORITE_INIT';
export const CHANGE_FAVORITE = 'CHANGE_FAVORITE';
export const CHANGE_FAVORITE_FILTER = 'CHANGE_FAVORITE_FILTER';

export const FILTER_POST_INIT = 'FILTER_POST_INIT';
export const FILTER_POST_START = 'FILTER_POST_START';
export const FILTER_POST_SUCCESS = 'FILTER_POST_SUCCESS';
export const FILTER_POST_FAIL = 'FILTER_POST_FAIL';
export const FILTER_POST = 'FILTER_POST'

export const FETCH_QUE_INIT = 'FETCH_QUE_INIT';
export const FETCH_QUE_START = 'FETCH_QUE_START';
export const FETCH_QUE_SUCCESS = 'FETCH_QUE_SUCCESS';
export const FETCH_QUE_FAIL = 'FETCH_QUE_FAIL';
export const FETCH_QUE = 'FETCH_QUE';

export const CHANGE_FAVORITE_QUE_INIT = 'CHANGE_FAVORITE_QUE_INIT';
export const CHANGE_FAVORITE_QUE = 'CHANGE_FAVORITE_QUE';
export const CHANGE_FAVORITE_FILTERQUE = 'CHANGE_FAVORITE_FILTERQUE';

export const FILTER_QUE_INIT = 'FILTER_QUE_INIT';
export const FILTER_QUE_START = 'FILTER_QUE_START';
export const FILTER_QUE_SUCCESS = 'FILTER_QUE_SUCCESS';
export const FILTER_QUE_FAIL = 'FILTER_QUE_FAIL';
export const FILTER_QUE = 'FILTER_QUE';

export const FETCH_GRP_INIT = 'FETCH_GRP_INIT';
export const FETCH_GRP_START = 'FETCH_GRP_START';
export const FETCH_GRP_SUCCESS = 'FETCH_GRP_SUCCESS';
export const FETCH_GRP_FAIL = 'FETCH_GRP_FAIL';
export const FETCH_GRP = 'FETCH_GRP';

export const FILTER_GRP_INIT = 'FILTER_GRP_INIT';
export const FILTER_GRP_START = 'FILTER_GRP_START';
export const FILTER_GRP_SUCCESS = 'FILTER_GRP_SUCCESS';
export const FILTER_GRP_FAIL = 'FILTER_GRP_FAIL';
export const FILTER_GRP = 'FILTER_GRP';

export const FETCH_HELPMEQUE_INIT = 'FETCH_HELPMEQUE_INIT';
export const FETCH_HELPMEQUE_START = 'FETCH_HELPMEQUE_START';
export const FETCH_HELPMEQUE_SUCCESS = 'FETCH_HELPMEQUE_SUCCESS';
export const FETCH_HELPMEQUE_FAIL = 'FETCH_HELPMEQUE_FAIL';
export const FETCH_HELPMEQUE = 'FETCH_HELPMEQUE';

export const CHANGE_FAVORITE_HELPMEQUE_INIT = 'CHANGE_FAVORITE_HELPMEQUE_INIT';
export const CHANGE_FAVORITE_HELPMEQUE = 'CHANGE_FAVORITE_HELPMEQUE';
export const CHANGE_FAVORITE_FILTERHELPMEQUE = 'CHANGE_FAVORITE_FILTERHELPMEQUE';

export const FILTER_HELPMEQUE_INIT = 'FILTER_HELPMEQUE_INIT';
export const FILTER_HELPMEQUE_START = 'FILTER_HELPMEQUE_START';
export const FILTER_HELPMEQUE_SUCCESS = 'FILTER_HELPMEQUE_SUCCESS';
export const FILTER_HELPMEQUE_FAIL = 'FILTER_HELPMEQUE_FAIL';
export const FILTER_HELPMEQUE = 'FILTER_HELPMEQUE';

export const FETCH_POET_INIT = 'FETCH_POET_INIT';
export const FETCH_POET_START = 'FETCH_POET_START';
export const FETCH_POET_SUCCESS = 'FETCH_POET_SUCCESS';
export const FETCH_POET_FAIL = 'FETCH_POET_FAIL';
export const FETCH_POET = 'FETCH_POET';

export const CHANGE_FAVORITE_POET_INIT = 'CHANGE_FAVORITE_POET_INIT';
export const CHANGE_FAVORITE_POET = 'CHANGE_FAVORITE_POET';
export const CHANGE_FAVORITE_FILTERPOET = 'CHANGE_FAVORITE_FILTERPOET';

export const FILTER_POET_INIT = 'FILTER_POET_INIT';
export const FILTER_POET_START = 'FILTER_POET_START';
export const FILTER_POET_SUCCESS = 'FILTER_POET_SUCCESS';
export const FILTER_POET_FAIL = 'FILTER_POET_FAIL';
export const FILTER_POET = 'FILTER_POET';

export const FETCH_USERS_INIT = 'FETCH_USERS_INIT';
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_USERS = 'FETCH_USERS';

export const USER_SELECT = 'USER_SELECT';
export const VIEW_USERS = 'VIEW_USERS';
export const REMOVE_USER = 'REMOVE_USER';
export const FILTER_USER_INIT = 'FILTER_USER_INIT';
export const FILTER_USER = 'FILTER_USER';
export const FILTER_USER_SELECT_INIT = 'FILTER_USER_SELECT_INIT';
export const FILTER_USER_SELECT = 'FILTER_USER_SELECT';
export const SHARE_ID = 'SHARE_ID';
export const DEFAULT_SHARE_PROPS = 'DEFAULT_SHARE_PROPS';
export const SHARE_USER_INIT = 'SHARE_USER_INIT';
export const SHARE_USER_START = 'SHARE_USER_START';
export const SHARE_USER_FAIL = 'SHARE_USER_FAIL';
export const SHARE_USER_SUCCESS = 'SHARE_USER_SUCCESS';

export const CHANGE_TAGS_PATH = 'CHANGE_TAGS_PATH';
export const FETCH_TAGS_INIT = 'FETCH_TAGS_INIT';
export const FETCH_TAGS_START = 'FETCH_TAGS_START';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAIL = 'FETCH_TAGS_FAIL';
export const FETCH_TAGS = 'FETCH_TAGS';

export const FETCH_TRD_INIT = 'FETCH_TRD_INIT';
export const FETCH_TRD_START = 'FETCH_TRD_START';
export const FETCH_TRD_SUCCESS = 'FETCH_TRD_SUCCESS';
export const FETCH_TRD_FAIL = 'FETCH_TRD_FAIL';
export const FETCH_TRD = 'FETCH_TRD';

export const CHANGE_FAVORITE_TRD_INIT = 'CHANGE_FAVORITE_TRD_INIT';
export const CHANGE_FAVORITE_TRD = 'CHANGE_FAVORITE_TRD';

export const FETCH_CATEG_INIT = 'FETCH_CATEG_INIT';
export const FETCH_CATEG_START = 'FETCH_CATEG_START';
export const FETCH_CATEG_SUCCESS = 'FETCH_CATEG_SUCCESS';
export const FETCH_CATEG_FAIL = 'FETCH_CATEG_FAIL';
export const FETCH_CATEG = 'FETCH_CATEG';

export const FETCH_CONV_INIT = 'FETCH_CONV_INIT';
export const FETCH_CONV_START = 'FETCH_CONV_START';
export const FETCH_CONV_SUCCESS = 'FETCH_CONV_SUCCESS';
export const FETCH_CONV_FAIL = 'FETCH_CONV_FAIL';
export const FETCH_CONV = 'FETCH_CONV';

export const HEADER_FORM_EXPAND = 'HEADER_FORM_EXPAND';
export const HEADER_FORM_SM = 'HEADER_FORM_SM';
export const HEADER_NAV_DEFAULT = 'HEADER_NAV_DEFAULT'

export const HEADER_ADD_NEW = 'HEADER_ADD_NEW';

export const FETCH_NOTIFY_INIT = 'FETCH_NOTIFY_INIT';
export const FETCH_NOTIFY_START = 'FETCH_NOTIFY_START';
export const FETCH_NOTIFY_SUCCESS = 'FETCH_NOTIFY_SUCCESS';
export const FETCH_NOTIFY_FAIL = 'FETCH_NOTIFY_FAIL';
export const FETCH_NOTIFY = 'FETCH_NOTIFY';

export const CHANGE_FAVORITE_NOTIFY_INIT = 'CHANGE_FAVORITE_NOTIFY_INIT';
export const CHANGE_FAVORITE_NOTIFY = 'CHANGE_FAVORITE_NOTIFY';

export const SHOW_NAV_LIST = 'SHOW_NAV_LIST';
export const FETCH_NAVLIST_INIT = 'FETCH_NAVLIST_INIT';
export const FETCH_NAVLIST_START = 'FETCH_NAVLIST_START';
export const FETCH_NAVLIST_SUCCESS = 'FETCH_NAVLIST_SUCCESS';
export const FETCH_NAVLIST_FAIL = 'FETCH_NAVLIST_FAIL';
export const FETCH_NAVLIST = 'FETCH_NAVLIST';

export const SHOW_USER_OPTION = 'SHOW_USER_OPTION';

export const FETCH_MAINACTIVE_INIT = 'FETCH_MAINACTIVE_INIT';
export const FETCH_MAINACTIVE = 'FETCH_MAINACTIVE';
export const DEFAULT_MAINACTIVE_INIT = 'DEFAULT_MAINACTIVE_INIT';
export const DEFAULT_MAINACTIVE = 'DEFAULT_MAINACTIVE';

export const FETCH_NOTIFY_ACTIVE_INIT = 'FETCH_NOTIFY_ACTIVE_INIT';
export const FETCH_NOTIFY_ACTIVE = 'FETCH_NOTIFY_ACTIVE';
export const DEFAULT_NOTIFYACTIVE_INIT = 'DEFAULT_NOTIFYACTIVE_INIT';
export const DEFAULT_NOTIFYACTIVE = 'DEFAULT_NOTIFYACTIVE';
export const FETCH_SHARE_ACTIVE_INIT = 'FETCH_SHARE_ACTIVE_INIT';
export const FETCH_SHARE_ACTIVE = 'FETCH_SHARE_ACTIVE';