export const CHECK_AUTH_INIT = 'CHECK_AUTH_INIT';
export const CHECK_AUTH = 'CHECK_AUTH';
export const CHECK_USERIMG = 'CHECK_USERIMG';
export const CHECK_USERNAME = 'CHECK_USERNAME';

export const HEADER_FORM_EXPAND = 'HEADER_FORM_EXPAND';
export const HEADER_FORM_SM = 'HEADER_FORM_SM';
export const HEADER_NAV_DEFAULT = 'HEADER_NAV_DEFAULT'

export const HEADER_FILTER_INIT = 'HEADER_FILTER_INIT';
export const HEADER_FILTER_START = 'HEADER_FILTER_START';
export const HEADER_FILTER_FAIL = 'HEADER_FILTER_FAIL';
export const HEADER_FILTER = 'HEADER_FILTER';
export const HEADER_FILTER_CLOSE = 'HEADER_FILTER_CLOSE';

export const HEADER_ADD_NEW = 'HEADER_ADD_NEW';

export const FETCH_NOTIFY_INIT = 'FETCH_NOTIFY_INIT';
export const FETCH_NOTIFY_START = 'FETCH_NOTIFY_START';
export const FETCH_NOTIFY_SUCCESS = 'FETCH_NOTIFY_SUCCESS';
export const FETCH_NOTIFY_FAIL = 'FETCH_NOTIFY_FAIL';
export const FETCH_NOTIFY = 'FETCH_NOTIFY';

export const CHANGE_FAVORITE_NOTIFY_INIT = 'CHANGE_FAVORITE_NOTIFY_INIT';
export const CHANGE_FAVORITE_NOTIFY_START = 'CHANGE_FAVORITE_NOTIFY_START';
export const CHANGE_FAVORITE_NOTIFY_FAIL = 'CHANGE_FAVORITE_NOTIFY_FAIL';
export const CHANGE_FAVORITE_NOTIFY = 'CHANGE_FAVORITE_NOTIFY';

export const SHOW_NAV_LIST = 'SHOW_NAV_LIST';
export const FETCH_NAVLIST_INIT = 'FETCH_NAVLIST_INIT';
export const FETCH_NAVLIST_START = 'FETCH_NAVLIST_START';
export const FETCH_NAVLIST_SUCCESS = 'FETCH_NAVLIST_SUCCESS';
export const FETCH_NAVLIST_FAIL = 'FETCH_NAVLIST_FAIL';
export const FETCH_NAVLIST = 'FETCH_NAVLIST';

export const SHOW_USER_OPTION = 'SHOW_USER_OPTION';

export const FETCH_SHARE_ACTIVE_INIT = 'FETCH_SHARE_ACTIVE_INIT';
export const FETCH_SHARE_ACTIVE = 'FETCH_SHARE_ACTIVE';
export const RESET_ACTIVE_INIT = 'RESET_ACTIVE_INIT';
export const RESET_ACTIVE = 'RESET_ACTIVE';

export const FETCH_NOTIFY_ACTIVE_INIT = 'FETCH_NOTIFY_ACTIVE_INIT';
export const FETCH_NOTIFY_ACTIVE = 'FETCH_NOTIFY_ACTIVE';
export const DEFAULT_NOTIFYACTIVE_INIT = 'DEFAULT_NOTIFYACTIVE_INIT';
export const DEFAULT_NOTIFYACTIVE = 'DEFAULT_NOTIFYACTIVE';

export const FETCH_CNT_INIT = 'FETCH_CNT_INIT';
export const FETCH_CNT_START = 'FETCH_CNT_START';
export const FETCH_CNT_RESET = 'FETCH_CNT_RESET';
export const FETCH_CNT_FAIL = 'FETCH_CNT_FAIL';
export const FETCH_CNT = 'FETCH_CNT';

export const FETCH_MEMBER_INIT = 'FETCH_MEMBER_INIT';
export const FETCH_MEMBER_START = 'FETCH_MEMBER_START';
export const FETCH_MEMBER_RESET = 'FETCH_MEMBER_RESET';
export const FETCH_MEMBER_FAIL = 'FETCH_MEMBER_FAIL';
export const FETCH_MEMBER = 'FETCH_MEMBER';

export const FETCH_CHAT_INIT = 'FETCH_CHAT_INIT';
export const FETCH_CHAT_START = 'FETCH_CHAT_START';
export const FETCH_CHAT_RESET = 'FETCH_CHAT_RESET';
export const FETCH_CHAT_FAIL = 'FETCH_CHAT_FAIL';
export const FETCH_CHAT = 'FETCH_CHAT';
export const FETCH_GROUP_INIT = 'FETCH_GROUP_INIT';
export const FETCH_GROUP_START = 'FETCH_GROUP_START';
export const FETCH_GROUP_FAIL = 'FETCH_GROUP_FAIL';
export const FETCH_GROUP = 'FETCH_GROUP';
export const FILTER_GROUP = 'FILTER_GROUP';
export const FETCH_GROUP_NOTIFY = 'FETCH_GROUP_NOTIFY';
export const ADD_NEW_CHAT = 'ADD_NEW_CHAT';
export const SHOW_AUDIO_REC = 'SHOW_AUDIO_REC';
export const SEARCH_CHAT = 'SEARCH_CHAT';
export const SHOW_EMOJI_BACKDROP = 'SHOW_EMOJI_BACKDROP';
export const CLOSE_CHAT_BACKDROP = 'CLOSE_CHAT_BACKDROP'
export const CHECK_LINK_INIT = 'CHECK_LINK_INIT';
export const CHECK_LINK = 'CHECK_LINK';
export const RESET_LINK = 'RESET_LINK';
export const CHAT_DISCONNECT = 'CHAT_DISCONNECT';
export const CHAT_CONNECT = 'CHAT_CONNECT';
export const UPLOAD_MUSIC = 'UPLOAD_MUSIC'
export const UPLOAD_VIDEO = 'UPLOAD_VIDEO'
export const SHARE_LOCATION = 'SHARE_LOCATION'
export const UPLOAD_DOC = 'UPLOAD_DOC'

export const CHANGE_TAB = 'CHANGE_TAB';
export const USER_TYPING = 'USER_TYPING';
export const SHOW_ADD_BACKDROP= 'SHOW_ADD_BACKDROP';
export const SHOW_USER_BACKDROP= 'SHOW_USER_BACKDROP';
export const CLOSE_BACKDROP= 'CLOSE_BACKDROP';

export const FILTER_USER_INIT = 'FILTER_USER_INIT';
export const FILTER_USER = 'FILTER_USER';
export const FILTER_USER_SELECT_INIT = 'FILTER_USER_SELECT_INIT';
export const FILTER_USER_SELECT = 'FILTER_USER_SELECT';

export const FILTER_MEMBER_INIT = 'FILTER_MEMBER_INIT';
export const FILTER_MEMBER = 'FILTER_MEMBER';

export const FETCH_USERS_INIT = 'FETCH_USERS_INIT';
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_USERS = 'FETCH_USERS';

export const USER_SELECT = 'USER_SELECT';
export const VIEW_USERS = 'VIEW_USERS';
export const REMOVE_USER = 'REMOVE_USER';
export const SET_GRP_INFO = 'SET_GRP_INFO';
export const SHARE_ID = 'SHARE_ID';
export const RESET_INPUT_FILTER = 'RESET_INPUT_FILTER';
export const CHANGE_CNT_INIT = 'CHANGE_CNT_INIT';
export const CHANGE_CNT_FAIL = 'CHANGE_CNT_FAIL';
export const CHANGE_CNT_STARTINIT = 'CHANGE_CNT_STARTINIT';
export const CHANGE_CNT_START = 'CHANGE_CNT_START';
export const CHANGE_CNT_CANCEL = 'CHANGE_CNT_CANCEL';
export const CHANGE_CNT_RESET= 'CHANGE_CNT_RESET';
export const CHANGE_CNT = 'CHANGE_CNT';
export const REMOVE_REQUEST = 'REMOVE_REQUEST';

export const FETCH_INFO_INIT = 'FETCH_INFO_INIT';
export const FETCH_INFO_START = 'FETCH_INFO_START';
export const FETCH_INFO_FAIL = 'FETCH_INFO_FAIL';
export const FETCH_INFO = 'FETCH_INFO';

export const DELETE_CHAT_INIT = 'DELETE_CHAT_INIT';
export const DELETE_CHAT_START = 'DELETE_CHAT_START';
export const DELETE_CHAT_FAIL = 'DELETE_CHAT_FAIL';
export const DELETE_CHAT = 'DELETE_CHAT';
export const CHAT_REMOVED = 'CHAT_REMOVED';

export const FETCH_PVTUSER_INIT = 'FETCH_PVTUSER_INIT';
export const FETCH_PVTUSER_START = 'FETCH_PVTUSER_START';
export const FETCH_PVTUSER_FAIL = 'FETCH_PVTUSER_FAIL';
export const FETCH_PVTUSER_RESET = 'FETCH_PVTUSER_RESET';
export const FETCH_PVTUSER = 'FETCH_PVTUSER';
export const FILTER_PVTUSER = 'FILTER_PVTUSER';
export const RESET_PVTINPUT_FILTER = 'RESET_PVTINPUT_FILTER';

export const RESET_MODEL = 'RESET_MODEL';
export const SHOW_SIDE_NAV =  'SHOW_SIDE_NAV';
export const CLOSE_SIDE_NAV =  'CLOSE_SIDE_NAV';
export const HOLD_CHAT =  'HOLD_CHAT';
export const RELEASE_CHAT =  'RELEASE_CHAT';

export const UPLOAD_MEDIA_FAIL = 'UPLOAD_MEDIA_FAIL';
export const UPLOAD_MEDIA_START = 'UPLOAD_MEDIA_START';
export const UPLOAD_MEDIA_CANCEL = 'UPLOAD_MEDIA_CANCEL';
export const UPLOAD_MEDIA = 'UPLOAD_MEDIA';
export const UPLOAD_MEDIA_SET = 'UPLOAD_MEDIA_SET';

export const GROUP_NOTIFY = 'GROUP_NOTIFY';
export const USER_NOTIFY = 'USER_NOTIFY';

export const FETCH_CHATDET_INIT = 'FETCH_CHATDET_INIT';
export const FETCH_CHATDET = 'FETCH_CHATDET';
export const FETCH_CHATDET_START = 'FETCH_CHATDET_START';
export const FETCH_CHATDET_FAIL = 'FETCH_CHATDET_FAIL';
export const SHOW_CHATDET = 'SHOW_CHATDET';

export const CREATE_CHAT_INIT = 'CREATE_CHAT_INIT';
export const CREATE_CHAT = 'CREATE_CHAT';
export const CREATE_CHAT_START = 'CREATE_CHAT_START';
export const CREATE_CHAT_FAIL = 'CREATE_CHAT_FAIL';

export const RESEND_CHAT_INIT = 'RESEND_CHAT_INIT';
export const RESET_RESEND_CHAT = 'RESET_RESEND_CHAT';